[build]
  base = "."
  publish = "client/build"
  command = "chmod +x build.sh && ./build.sh"

[build.environment]
  NODE_VERSION = "18"
  CI = "true"
  NODE_OPTIONS = "--max-old-space-size=3008"
  NPM_CONFIG_PROGRESS = "false"
  NPM_CONFIG_LOGLEVEL = "error"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"